#cloud-config
# Add groups to the system
# Adds the ubuntu group with members 'root' and 'sys'
# and the empty group hashicorp.
groups:
  - ubuntu: [root,sys]
  - hashicorp
# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: deploy
    gecos: deploy
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys: 
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC3HihzD4/seo5A+xwxbhX90UZzkk7WMKT9UZEf1ag2lIuACgeCIHP0qENVDFhYHQtHgAA1H1LPUTThUNmF+SnRC+n3nsitF6hO8/XdRZCfD2TPZ0GDKshGFUGtjDlGDLBhXBMAJxcxEg+ETlZFPiIifwyyuAaj8WMc4qUd7Cv0wlJ+vtWdg+xU4XIxnZ1MaP5fJLKQPgcee/Jgz+e8vchkgENLslDbc7swxLH+E1nGthVFhdFXzJtx2NN7ksXW0dnQznipKRoRyaq11Sj45kqKc31rAM2F6o+qVMuH42t6nlM0OLVbRLQgVM7AJKG8U0L9UY1xEJOING6ukEZ1ToIJZCX2/+tZTt+zNABsG2juV6o+GSL+5kS9Y+8GwkEAhvHvQVYsXUKT3+1g9qiRAtzfnnZtg5qEgmdVk5T10ttITPvsUjKfzpCqD5/erfFqScZVj7W2jmCMLyevtV8BaOwQQt/MjivdOUIx+gO0jj73xp8IeUMid1lnYhMd9q2GBf8= kelbo@DESKTOP-HBDHRAG
# Downloads the golang package
packages:
  - python3
runcmd:
  -   alias python=python3